### ISSUE TITLE
Liveswitch repo for submitting client Issues?

### ISSUE THREAD

**Issue by karltaylor** [liveswitch/liveswitch-connect#34]
Hello,

I am in the process of integrating the Liveswitch Javascript SDK into an application.

I've come across several issues that I've needed to submit but unfortunately, I haven't had much luck with the Liveswitch support.

Would it be possible to create liveswitch client repository to track issues more efficiently?

Kind regards,

Karl

**Comment by fm-adam** [comment]
Hello!

We are happy to help. If you are currently trialing LiveSwitch, you can submit support tickets, or general technical questions about the software, to support@frozenmountain.com. Use the email address you used when signing up for your trial.

If you prefer, there is also a LiveSwitch Support Community forum available [here](https://support.frozenmountain.com/hc/en-us/community/topics/115000218013-LiveSwitch-Support). Questions submitted to the Community forum are answered either by LiveSwitch support or by other developers in the community.

Thanks

**Comment by karltaylor** [comment]
Hi "fm-adam"

I am not trialing LiveSwitch. My colleague has had no luck with frozen mountain support. 

Are you not open to the idea of having Client SDK repositories to track & triage issues?
