### ISSUE TITLE
lsconnect won't re-establish when connection is broken

### ISSUE THREAD

**Issue by BruceWheaton** [liveswitch/liveswitch-connect#43]
Testing on the tip, Windows 10/64-bit, with ndirender verb. If an SFU upstream connection using a media-id is broken, when the connection re-establishes, lsconnect does not complete the connection. The console shows:

NDIRenderer connection failed. System exception: Connection closed. (ConnectionRemoteFailure sfuInvalidUpstream.)

Console then shows the connection trying to initialize again and again. Killing and restarting lsconnect works.
Similar symptom when activating lsconnect before connection.
[Caveat - using lsconnect ndirender with a media-id, which I was told works, but isn't listed in current docs]

**Comment by avenema** [comment]
@BruceWheaton

**Comment by avenema** [comment]
@BruceWheaton thank you for the report on this. A fix is incoming.
